### ISSUE TITLE
New release with single-cell-bulk.rs?

### ISSUE THREAD

**Issue by dlaehnemann** [PROSIC/libprosic#10]
For eventually getting a ProSolo release that can go into bioconda, I'd like to have a clear release of libprosic with the single cell bulk changes in. Also, a dependency on a specific release version of rust-bio would be needed, I think.

**Comment by dlaehnemann** [comment]
Bump of the request for a single-cell-bulk model release of libprosic. Or should I go about this myself? Any pointers for that?

**Comment by johanneskoester** [comment]
Sorry for the delay. I can do a new release. But I have only very limited time until monday. To speed things up, you could update the changelogs for me.

**Comment by dlaehnemann** [comment]
Should I just do that on my local master branch and push it directly to the master, here?

**Comment by johanneskoester** [comment]
Just as a pull request.

**Comment by dlaehnemann** [comment]
Sorry for the basic question: So create a new branch (e.g. `prepare-v0.4.0`) and then a pull request from there? Or did you have a different route in mind?

**Comment by johanneskoester** [comment]
That's fine, yes.

**Comment by dlaehnemann** [comment]
Solved by #11 and the resulting release.
