### ISSUE TITLE
FDR over sets of `Event`s

### ISSUE THREAD

**Issue by dlaehnemann** [PROSIC/libprosic#13]
Instead of doing the FDR threshold / cutoff calculations for only a single `Event`, we want to enable doing it over sets of `Event`s. I.e. we want to sum up the probabilities of this set of `Event`s at each site and use that to generate the probability distribution for the cutoffs.

@johanneskoester, I was wondering, if this shouldn't just be a change to `collect_prob_dist()` in the main `utils.rs`, i.e. making this work on `&Vec<E>` instead of `&E `:

https://github.com/PROSIC/libprosic/blob/e9dc04a5b30e85fed966ec17bb19a6eb72962f44/src/utils.rs#L177-L180

I think anything else would be hacking around this in this line with weird vectors of vectors:

https://github.com/PROSIC/libprosic/blob/e9dc04a5b30e85fed966ec17bb19a6eb72962f44/src/estimation/fdr/ev.rs#L37

Instead, we just need one distribution afterwards that `collect_prob_dist()` could create. Am I making sense?

**Comment by johanneskoester** [comment]
Yes, that makes absolute sense. I totally agree.

**Comment by dlaehnemann** [comment]
Closed by #14
