### ISSUE TITLE
arbitrary ALPHAS via command-line or finer resolution of small FDRs?

### ISSUE THREAD

**Issue by dlaehnemann** [PROSIC/libprosic#25]
I have the case where I would like to further resolve FDRs smaller than 0.01, and the current definition only goes down to that value:

https://github.com/PROSIC/libprosic/blob/e3da0d58729a29bfcb3a246ecacf6986f78ff7ff/src/estimation/fdr/mod.rs#L7-L36

As a first step, I would suggest adding the following values to this static definition of ALPHAS (unless there is some good reason that `0.01` is the smallest value, e.g. a methodological limitation?!):
```
0.00001,
0.00005,
0.0001,
0.0005,
0.001,
0.005,
```

In a second step (or maybe directly?), we could allow for passing extra (or all) alpha values on the command line.

Any objections? Any further considerations to be made?

**Comment by johanneskoester** [comment]
Makes sense, feel free to create a PR for the extra hardcoded values. Making this configurable by allowing `--alphas 0.01 0.05 ...` is a good idea as well, but we can indeed do that later.

**Comment by dlaehnemann** [comment]
I just realised that Rust only auto-implements the Trait `IntoIterator` for arrays of length up to 32. This currently leaves me only 4 extra values that I can add. Would it be OK to remove current entries `0.65` and `0.75` in order to add more resolution closer to zero? In my data, the are around these higher values does not see any change of FDR filter level any more...

**Comment by dlaehnemann** [comment]
My suggestion in PR #26 now is to remove two more higher FDR points in exchange for more resolution in the very low range.

**Comment by dlaehnemann** [comment]
P.S.: I'd keep this issue open beyond PR #26 to remind us of the command-line option plan.

**Comment by dlaehnemann** [comment]
This is basically resolved with PR #45
