### ISSUE TITLE
release 0.7.0

### ISSUE THREAD

**Issue by dlaehnemann** [PROSIC/libprosic#49]
With all the recent changes, doesn't it make sense to create a new release of `libprosic`?

For me, this would be useful for a stable release of ProSolo, pinning down clear versions of all the dependencies. To achieve that, this would currently also require a new release over at [rust-htslib](https://github.com/rust-bio/rust-htslib), because we need to have the recent rust-htslib addition of `remove_alleles()` in the current libprosic:
<https://github.com/rust-bio/rust-htslib/commit/99166dbdd73381d4910a42346fe9f9074034a1da>
Apart from that, I'd gladly create a release branch, once #48 is merged.

**Comment by johanneskoester** [comment]
Good point. I will take care of the releases once I am back from vacation (1. Nov).

**Comment by dlaehnemann** [comment]
Thanks -- and in the meantime I'll probably just create a beta version of prosolo for myself...

**Comment by dlaehnemann** [comment]
Closed by #50 and the following cargo release.
